name: Backend API Build and Push

on:
  push:
    branches: [main, develop]
    paths: ['backend/**']
  pull_request:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

env:
  DOCKER_REPO: docker.io/youkim7/backend
  WORKING_DIRECTORY: ./backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'eclipse-temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn clean test

      - name: Run checkstyle
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn checkstyle:check

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'eclipse-temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build application
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tags
        id: meta
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tags=${{ env.DOCKER_REPO }}:latest,${{ env.DOCKER_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "primary=${{ env.DOCKER_REPO }}:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ env.DOCKER_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "primary=${{ env.DOCKER_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure CLI login (Service Principal)
        if: github.ref == 'refs/heads/main'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az login --service-principal \
              -u "${{ secrets.AZURE_CLIENT_ID }}" \
              -p "${{ secrets.AZURE_CLIENT_SECRET }}" \
              --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Update Container App (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          az containerapp update \
            --name ca-backend \
            --resource-group rg-burgerbuilder-prod \
            --image "${{ steps.meta.outputs.primary }}"
